services:
  postgres:
    image: postgres:15-alpine
    container_name: live-support-postgres
    environment:
      POSTGRES_DB: live_support_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d live_support_dashboard"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
